#!/bin/bash

if [ -z "$1" ]; then
    echo "Error: $(basename "$0") requires an argument" >&2
    exit 1
fi

# Add dir tree to path
PATH=${PATH}:$(find "$1" -type d | tr '\n' ':' | sed 's/:$//')
export PATH

