#!/bin/bash

if [ -z "$logFile" ]; then
    exitWith 1 "Error: the variable 'logFile' has no value. Exiting."
fi

require pwd

# Print header
echo ====  Start log: `date '+%Y-%m-%d %H:%M:%S'`
echo ==== Logscript: "$(readlink -f "$0")"
if [ "$#" -gt 0 ]; then
    echo ==== Command: $*
fi
echo ==== Working directory: "$(pwd)"
echo ==== Logfile: "$(readlink -f "$logFile")"
echo

# Run the command and log its output
startTime=$(date +%s)

if [ "$#" -gt 0 ]; then
    $* 2>&1
    export logopExitStatus=$?
else
    cat <&0
fi

endTime=$(date +%s)

# Print footer
echo
if [ "$#" -gt 0 ]; then
    echo ====  Exit status: $logopExitStatus
fi
echo ====  Elapsed: $(elapsedTime $startTime $endTime L)
echo ====  End log: `date '+%Y-%m-%d %H:%M:%S'`
