#!/bin/bash

. rabot-common
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-common" >&2
  exit 1
fi

checkForHelp $1

: << DOCSTRING
Usage: $(basename "$0") [TEXT]

'$(basename "$0")' reads from stdin and after reaching EOF
displays a dialog box with all lines read as items in a
menu. When you select an item, '$(basename "$0")' prints
the item on stdout and terminates.

When pressing "Cancel" '$(basename "$0")' terminates without
printing any output.

With the optional argument TEXT you can put an explanatory
text in the dialog. The default is the empty string.

This script depends on the command-line tool 'dialog'.

Examples:

Choose one file in ~/log to view with 'less':

    $ lfiles ~/log | pick1 | xargs less

See also: 'pickn', 'lfiles'
DOCSTRING

require dialog

i=0
while read line; do
    item[$i]="$line"
    items="$items $i \"$line\""
    i=$(expr $i + 1)
done

tags=$(bash -c "dialog --keep-tite --no-tags --title \"pick1\" --menu \"$1\" 20 60 10 $items 3>&1 1>&2 2>&3 3>&-")

while read tag; do
    if [ -n "$tag" ]; then
        echo ${item[$tag]}
    fi
done < <(echo $tags | tr ' ' $'\n')
