#!/bin/bash

. rabot-common
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-common" >&2
  exit 1
fi

checkForHelp $1

: << DOCSTRING
Usage: $(basename "$0")

'$(basename "$0")' updates the file 'README.rst' containing
the 'rabot' documentation. This can be done before
committing to version control.
DOCSTRING

toolsDirtree="$(rabot-vars rabotDir)"
docScripts $toolsDirTree > README.rst
git add README.rst
