#!/bin/bash

. rabot-common
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-common" >&2
  exit 1
fi

checkForHelp $1
minNumArgs 1 $#

: << DOCSTRING
Usage: $(basename "$0") COMMAND [ARG1]...

'$(basename "$0")' performs COMMAND with its arguments in
every directory of the tree rooted in the current working
directory.

Example:

    user@host ~ $ walkdir pwd
    /home/user
    /home/user/mydir
    /home/user/myotherdir

See also: 'walkdird'
DOCSTRING

fun-walkdir $*
