#!/bin/bash

. rabot-common
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-common" >&2
  exit 1
fi

checkForHelp $1

: << DOCSTRING
Usage: $(basename $0)

Compress the contents of the Current Working Directory (CWD)
to a .zip file stored in its parent directory.

'$(basename $0)' performs the following actions:

1. Remove temporary files from the CWD by running the script
   'clean-this'.

2. 'cd' into the parent directory of the CWD and run
   the script 'zip-folder' on the former CWD.

Example:

    user@host ~/myfolder $ zip-this
    /home/user/myfolder_20140522225226_0fg.zip

See also: 'zip-folder', 'tgz-this'
DOCSTRING

require clean-this
require zip-folder

folderPath=$(pwd)
folderName=$(basename $folderPath)
fullScriptPath=$(readlink -f $0)

# 1.
clean-this
exitOnError 1 "The script 'clean-this' returned an error."

# 2.
cd ..
exitOnError 1 "Could not perform 'cd ..'"

if [ "$(pwd)" = "$folderPath" ]; then
  echo $fullScriptPath: Error: could not cd into parent directory of \'$folderPath\'>&2
  exit -1
fi

zip-folder "$folderName" .
exitOnError 1 "The script 'tgz-folder' returned an error"


